Creating pokelist page, and routes
ashcrysis/pokeRuby pull request #1
Opened 2024-05-23 14:29 UTC by ashcrysis

2024-05-24 13:01 UTC, pbressan13 requested changes
O projeto está excelente e você está muito avançada nas coisas, já fez ajustes ontem mesmo que eu tinha pensado em sugerir, e você já tinha feito, somente dei algumas sugestões de organização de código.

Queria que também você fixasse o conceito mais de ruby on rails como um todo, pq o creme de la creme da aplicação tá no javascript, então de repente, poderíamos criar uma página a parte, em que você dá um fetch na api dos pokemons, e cria o pokemon no seu banco de dados, ai teríamos um model chamado Pokemon, e com os atributos da própria api, mas isso são idéias que a gente pode discutir daqui a pouco

2024-05-24 13:01 UTC, pbressan13 commented on app/controllers/pokemon_controller.rb
> +    if response.code == 200
Essa var sprite_url, acredito que não está sendo usada pra nada, poderia retirar

2024-05-24 13:01 UTC, pbressan13 commented on app/controllers/pokemon_controller.rb
> +    if response.code == 200
A função `index`, por convenção, seria usada para listar todos os pokemons, ou pelo menos mais de um.

Para listar um pokemon, o ideal seria criar uma função chamada `show`, e usar na rota para busca

2024-05-24 13:01 UTC, pbressan13 commented on app/controllers/pokemon_controller.rb
> +        species_call = HTTParty.get("https://pokeapi.co/api/v2/pokemon-species/#{pokemon_name.strip().split('-')[0]}")
non-blocking... o endereço da api do pokemon é chamada diversas vezes, uma idéia boa seria criar uma constante, como POKEMON_API = "https://pokeapi.co/api/v2/pokemon", e toda vez que for chamar ela, como nesse caso, seria POKEMON_API + argumentos

2024-05-24 13:01 UTC, pbressan13 commented on app/controllers/pokemon_controller.rb
> +      @flavor_text = ""
Uma idéia boa, seria criar funções privadas e callbacks para organizar o código

Ex:   

Antes de começar as funções

`  before_action :pokemon_name, only: [:show, :index]`


Depois das funções públicas

```
private

  def pokemon_name
    @pokemon_name = pokemon_params[:pokemon_name] || 'bulbasaur'
  end

   def pokemon_params
    params.permit(:pokemon_name, :commit)
  end
```

Essa é uma idéia, dá pra gente quebrar essa função maior em funções menores privadas para gerenciar a responsabilidade de cada uma, tem uma convenção do rails (que nem sempre dá pra se cumprir, digasse de passagi), que o ideal é que uma função tenha no máximo 10 linhas

Daria para colocar uma função de all_pokemon, uma função de validação de entrada de argumentos de pokemon ( do princípio de nunca confie na resposta de uma fonte externa), etc

2024-05-24 13:01 UTC, pbressan13 commented on app/javascript/pokeFetch.js
> +function start_page(){
Vi que colocou o javascript agora num arquivo .js ao invés do erb, ia pedir pra você fazer isso mesmo, mas você foi mais rápida rs

2024-05-24 13:01 UTC, pbressan13 commented on app/javascript/pokeFetch.js
> +        anchor.href = `http://127.0.0.1:3000/pokemon?pokemon_name=${pokemon.name.toLowerCase()}&commit=Search`;
Ideal que a gente não fixe as URLs desse jeito `http://127.0.0.1:3000/pokemon`, pois se mudarmos de ambiente, colocarmos isso na nuvem, isso iria quebrar

2024-05-24 13:01 UTC, pbressan13 commented on app/views/pokemon/index.html.erb
> +<body id="main_page_body">
Vi que para essa nova versão, você começou a usar mais a sintaxe do erb ao invés do html, o que era algo que ia comentar, muito bom!

2024-05-24 13:10 UTC, ashcrysis commented on app/controllers/pokemon_controller.rb
> +    if response.code == 200
Removi, vou subir na proxima commit!

2024-05-24 13:11 UTC, ashcrysis commented on app/javascript/pokeFetch.js
> +function start_page(){
KKKKKKKKKKKKK tava muito agoniada com muita coisa junta, obrigada

2024-05-24 13:13 UTC, ashcrysis commented on app/javascript/pokeFetch.js
> +        anchor.href = `http://127.0.0.1:3000/pokemon?pokemon_name=${pokemon.name.toLowerCase()}&commit=Search`;
alterei pra "/pokemon?pokemon_name=${pokemon.name.toLowerCase()}&commit=Search`"

2024-05-28 13:16 UTC, pbressan13 approved these changes
Comentários mais non-blocking, mas está MUITO bom!

2024-05-28 13:16 UTC, pbressan13 commented on app/controllers/favorites_controller.rb
> +  end
Bom seria colocar 1 linha de separação entre os métodos

2024-05-28 13:16 UTC, pbressan13 commented on config/routes.rb
> +  resources :favorites, only: [:create, :index]
```suggestion
  resources :favorites, only: [:create, :index, :destroy]
```

Colocando assim, você poderia tirar o delete 'favorites/clear', to: 'favorites#clear', as: 'clear_favorites', e depois renomear o método de clear para destroy

2024-05-28 13:35 UTC, ashcrysis commented on config/routes.rb
> +  resources :favorites, only: [:create, :index]
Posso por, mas em específico o clear deleta todos os favoritos do usuário e não só um em especifico, é basicamente uma limpa

2024-05-28 13:36 UTC, merged